version: "3.9"
services:
  zoo1:
    build: zookeeper
    ports:
      - "127.0.0.11:2180:2180"
    volumes:
      - "$PWD/kafka_distr:/opt/kafka"
      - "$PWD/zookeeper/data/zoo1:/opt/zookeeper"
    networks:
      - kafka-lab
  zoo2:
    build: zookeeper
    ports:
      - "127.0.0.12:2180:2180"
    volumes:
      - "$PWD/kafka_distr:/opt/kafka"
      - "$PWD/zookeeper/data/zoo2:/opt/zookeeper"
    networks:
      - kafka-lab
  zoo3:
    build: zookeeper
    ports:
      - "127.0.0.13:2180:2180"
    volumes:
      - "$PWD/kafka_distr:/opt/kafka"
      - "$PWD/zookeeper/data/zoo3:/opt/zookeeper"
    networks:
      - kafka-lab

  kafka1:
    build: kafka_server
    volumes:
      - "$PWD/kafka_distr:/opt/kafka"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - kafka-lab
    command: ["bin/kafka-server-start.sh", "config/server.properties", "--override", "broker.id=1"]
  kafka2:
    build: kafka_server
    volumes:
      - "$PWD/kafka_distr:/opt/kafka"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - kafka-lab
    command: ["bin/kafka-server-start.sh", "config/server.properties", "--override", "broker.id=2"]
  kafka3:
    build: kafka_server
    volumes:
      - "$PWD/kafka_distr:/opt/kafka"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - kafka-lab
    command: ["bin/kafka-server-start.sh", "config/server.properties", "--override", "broker.id=3"]

  kafka-sandbox:
    build: kafka_sandbox

networks:
  kafka-lab:
    name: "kafka-lab"